apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: welcome-lb-svc
  name: welcome-lb-svc
spec:
  ports:
  - name: welcome-loadbalancer
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: welcome-dep
  type: LoadBalancer
status:
  loadBalancer: {}
