apiVersion: v1
kind: Pod
metadata:
  labels:
    type: pod
    app: welcome
  name: welcome-pod
spec:
  containers:
  - image: nitinjilla/welcome
    name: welcome
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
